### ISSUE TITLE
AddAll keeps files it added open!

### ISSUE THREAD

**Issue by leo-stone** [jhoonb/archivex#19]
Hi all,

AddAll() does not close the files it added to the archive.
So the following use case is not implementable:
1. archive directory
2. remove directory (will fail cause all files still open)

my local fix in 
`func addAll(dir string, rootDir string, includeCurrentFolder bool, writerFunc ArchiveWriteFunc) error`:

after line 336 i added

`if file != nil {
	file.(*os.File).Close()
}`

**Comment by tooolbox** [comment]
Would you mind doing a pull request?  :)

**Comment by leo-stone** [comment]
well, after some struggeling, there you go
